Fix MacAddress and IP Check
Stolao/Npc_Release pull request #27
Opened 2017-09-11 03:31 UTC by sader1992

2017-09-13 21:58 UTC, Stolao commented on Daily_Reward/DailyReward.txt
>  			message strcharinfo(0),"[Daily Rewards]: Rewards are limited to "+.IPCheck+" per IP sorry.";
tab here

2017-09-13 21:58 UTC, Stolao commented on Daily_Reward/DailyReward.txt
>  			message strcharinfo(0),"[Daily Rewards]: Rewards are limited to "+.MacCheck+" per computer sorry.";
tab here

2017-09-13 22:00 UTC, Stolao requested changes
Can you please tabulate properly in the changes you made

also i pushed a slight optimization can you tweak to remove conflicts.

2017-09-13 22:00 UTC, Stolao commented on Daily_Reward/DailyReward.txt
>  			message strcharinfo(0),"[Daily Rewards]: Rewards are limited to "+.MacCheck+" per computer sorry.";
@sader1992

2017-09-13 22:43 UTC, Stolao commented on Daily_Reward/DailyReward.txt
>  			message strcharinfo(0),"[Daily Rewards]: Rewards are limited to "+.IPCheck+" per IP sorry.";
should be
`message strcharinfo(0),"[Daily Rewards]: Rewards are limited to 1 per IP sorry.";`

since you no longer compare size of ip check

2017-09-13 23:00 UTC, sader1992 commented
i am not very good at GitHub XD

2017-09-18 17:15 UTC, sader1992 commented on Daily_Reward/DailyReward.txt
> +			if(#LastDailyReward < .@MacCheck2){
this check i think it's not working good with .MinWait
i think it need something like (#LastDailyReward + .MinWait - .@i) <.@MacCheck2
and moving .@i from down to up then change the message to say the time needed before getting the new reward
i am testing right now

2017-09-18 17:24 UTC, sader1992 commented on Daily_Reward/DailyReward.txt
> +			if(#LastDailyReward < .@MacCheck2){
or saving the (#LastDailyReward or the max value from the other accounts) to a .@something after the gepard and ip check and changing the #LastDailyReward in the rest of the script to the new .@something ?

2017-12-17 17:55 UTC, closed without merging